name: dbt_cloud_sync

on:
  push:
    branches: [ main ] # Se activa al subir cambios a la rama principal

jobs:
  run_dbt_cloud:
    runs-on: ubuntu-latest
    
    env:
      # GitHub buscará esta "llave" en sus secretos
      MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install dbt-duckdb

      - name: Execute dbt Pipeline
        run: |
          cd dbt_project
          dbt seed --profiles-dir .
          dbt run --profiles-dir .
          dbt test --profiles-dir .