name: dbt_cloud_pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt
        run: |
          pip install dbt-duckdb

      - name: Run dbt Pipeline
        env:
          # IMPORTANTE: Aquí es donde GitHub lee tu "Secret" 
          # y se lo pasa a dbt para que MotherDuck no pida login manual
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: |
          cd dbt_project
          dbt seed --profiles-dir .
          dbt run --profiles-dir .
          dbt test --profiles-dir .